### ISSUE TITLE
Incorrect error message on enum parsing when a binwrite impl is missing

### ISSUE THREAD

**Issue by Raytwo** [jam1garner/binrw#99] opened 2022-02-19 19:16 UTC
While trying out binrw, I implemented a parser using the ``binrw`` attribute while I should have been using the ``binread`` one instead.

Due to missing a binwrite impl for my struct, I ended up getting an error message, but it was pointing out an error that wasn't relevant, which you can observe on this screenshot:
![image](https://user-images.githubusercontent.com/18125485/154815574-53325c54-6e62-4134-8246-10344e15a96b.png)

As you can see, the enum is properly defined, and the error is already addressed.

**Comment by jam1garner** [comment] 2022-02-27 07:19
Adding to this: the issue is that the BinWrite error is copy/pasted from the binread error

**Comment by csnover** [comment] 2022-08-23 04:21
The incorrect error has been fixed by #139 so this can be closed when that lands.

**Comment by csnover** [comment] 2022-08-23 05:20
This is fixed by c6931d02d60fe7aa4f634e69e4ecb1fecb047b5c. Thanks!

**Closed by csnover** 2022-08-23 05:20 UTC
Labels: bug, good first issue, diagnostics-issue
